void checkLyrics(int bar, int frame){
  if(bar==0 && frame==15)donmiguel.sing("hey!");
  if(bar==1 && frame==8)donmiguel.sing("been trying to meet you mmmmmm hmmmmm");
  //if(bar==2 && frame==0)donmiguel.sing("mmmmmm hmmmmm");
  if(bar==4 && frame==0)donmiguel.sing("hey!");
  if(bar==4 && frame==8)donmiguel.sing("must be a devil");
  if(bar==5 && frame==0)donmiguel.sing("between us");//
  if(bar==6 && frame==0)donmiguel.sing("or whores in my head");
  if(bar==7 && frame==0)donmiguel.sing("whores at the door");
  if(bar==8 && frame==0)donmiguel.sing("whores in my bed");
  if(bar==9 && frame==0)donmiguel.sing("but hey");
  if(bar==10 && frame==0)donmiguel.sing("where");
  if(bar==11 && frame==0)donmiguel.sing("have you");
  if(bar==12 && frame==0)donmiguel.sing("been");
  if(bar==14 && frame==0)donmiguel.sing("if you go!");
  if(bar==15 && frame==0)donmiguel.sing("i will surely die");
  if(bar==16 && frame==0)donmiguel.sing("we're chained");
  if(bar==17 && frame==0)donmiguel.sing("we're chained");
  if(bar==18 && frame==0)donmiguel.sing("we're chained");
  if(bar==19 && frame==0)donmiguel.sing("we're chained");
  if(bar==20 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==21 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==22 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==23 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==24 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==25 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==26 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==27 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==28 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==29 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==47 && frame==0)donmiguel.sing("uh");
  if(bar==48 && frame==8)donmiguel.sing("said the man to the lady");
  if(bar==50 && frame==0)donmiguel.sing("mmmmmm hmmmm");
  if(bar==51 && frame==0)donmiguel.sing("uh");
  if(bar==52 && frame==8)donmiguel.sing("said the lady to the man she adored");
  if(bar==54 && frame==0)donmiguel.sing("and the whores like a choir");
  if(bar==55 && frame==0)donmiguel.sing("go uh all night");
  if(bar==56 && frame==0)donmiguel.sing("and mary ain't you tired of this");
  if(bar==56 && frame==8)donmiguel.sing("uh");
  if(bar==57 && frame==0)donmiguel.sing("is");
  if(bar==58 && frame==0)donmiguel.sing("the");
  if(bar==59 && frame==0)donmiguel.sing("sound");
  if(bar==61 && frame==0)donmiguel.sing("that THE MOTHER MAKES");
  if(bar==62 && frame==0)donmiguel.sing("when the baby breaks");
  if(bar==63 && frame==0)donmiguel.sing("we're chained");
  if(bar==64 && frame==0)donmiguel.sing("we're chained");
  if(bar==65 && frame==0)donmiguel.sing("we're chained");
  if(bar==66 && frame==0)donmiguel.sing("we're chained");
  if(bar==67 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==68 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==69 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==70 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==71 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==72 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==73 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==74 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==75 && frame==0)donmiguel.sing("we're chained");// (chained)");
  if(bar==76 && frame==0)donmiguel.sing("we're chained");// (chained)");
}
